# Generated by Django 5.1.5 on 2025-12-31 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "blocked",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocked_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "blocker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocking",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["blocker"], name="social_bloc_blocker_846063_idx"),
                    models.Index(fields=["blocked"], name="social_bloc_blocked_67400d_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("blocker", "blocked"), name="uniq_block"),
                    models.CheckConstraint(
                        condition=models.Q(("blocker", models.F("blocked")), _negated=True),
                        name="chk_block_no_self",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Follow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "follower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "following",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["follower"], name="social_foll_followe_9bcca8_idx"),
                    models.Index(fields=["following"], name="social_foll_followi_3e6f69_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("follower", "following"), name="uniq_follow"),
                    models.CheckConstraint(
                        condition=models.Q(("follower", models.F("following")), _negated=True),
                        name="chk_follow_no_self",
                    ),
                ],
            },
        ),
    ]
